source 'https://rubygems.org'
ruby '2.4.2'

gem 'ruby-saml', '~> 1.9.0'
gem 'cucumber', '3.1.0'
gem 'rspec'
gem 'rspec-expectations', '3.7.0'
gem 'capybara', '2.17.0'
gem 'capybara-screenshot', '1.0.18'
gem 'selenium-webdriver', '3.8.0'
gem 'chromedriver-helper', '1.2.0'

